apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-green
  labels:
    app: analytics-service
    color: green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: analytics-service
      color: green
  template:
    metadata:
      labels:
        app: analytics-service
        color: green
    spec:
      containers:
        - name: analytics-service
          image: charukaiit/analytics-service:v1
          imagePullPolicy: Always
          env:
            - name: CLICKHOUSE_HOST
              value: "clickhouse"
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_DB
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICKHOUSE_PASSWORD
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /analytics/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
