apiVersion: apps/v1
kind: Deployment
metadata:
  name: program-service-green
  labels:
    app: program-service
    color: green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: program-service
      color: green
  template:
    metadata:
      labels:
        app: program-service
        color: green
    spec:
      containers:
        - name: program-service
          image: charukaiit/program-service:v2
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
