apiVersion: v1
kind: Service
metadata:
  name: new-event-frontend-service
spec:
  type: ClusterIP
  selector:
    app: new-event-frontend
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
