apiVersion: v1
kind: Service
metadata:
  name: new-event-frontend-blue-preview
spec:
  type: ClusterIP
  selector:
    app: new-event-frontend
    color: blue
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: new-event-frontend-green-preview
spec:
  type: ClusterIP
  selector:
    app: new-event-frontend
    color: green
  ports:
    - port: 80
      targetPort: 80
